// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLpq59sFMGHzJrGOxX_UTKAaiVFKDREk',
    appId: '1:130806800586:web:a3f090470a77e18e945433',
    messagingSenderId: '130806800586',
    projectId: 'mynotes-tutorial',
    authDomain: 'mynotes-tutorial.firebaseapp.com',
    storageBucket: 'mynotes-tutorial.appspot.com',
    measurementId: 'G-2PSWNPV02S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kxy3IpAlOHP3ZxSOD8qVH17q0M_M7mE',
    appId: '1:130806800586:android:213c016a79058bef945433',
    messagingSenderId: '130806800586',
    projectId: 'mynotes-tutorial',
    storageBucket: 'mynotes-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRS78-BvGo2rTaHMsv-xIjgtt9pp0M3U',
    appId: '1:130806800586:ios:4a2a85db0285a6c2945433',
    messagingSenderId: '130806800586',
    projectId: 'mynotes-tutorial',
    storageBucket: 'mynotes-tutorial.appspot.com',
    iosClientId: '130806800586-r9l6rsaiq156796f1u7gh7ljcehc9acd.apps.googleusercontent.com',
    iosBundleId: 'com.danish.mynotes',
  );
}
